/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 * @author JHONIER ARIAS
 */
public class vistaPropiedades extends javax.swing.JFrame {




    /**
     * Creates new form vistaPropiedades
     */
    public vistaPropiedades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPropiedades = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNOMBRE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBuscarPropiedad = new javax.swing.JTextField();
        txtDIRECCION = new javax.swing.JTextField();
        txtPRECIO = new javax.swing.JTextField();
        txtTAMANO = new javax.swing.JTextField();
        btnREGISTRAR = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminarPRO = new javax.swing.JButton();
        btnCancelarPRO = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtHABITACIONES = new javax.swing.JTextField();
        boXESTADO = new javax.swing.JComboBox<>();
        boxTIPOPRO = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaPropiedades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPropiedades);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 740, 310));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("PROPIEDADES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 202, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre Propiedad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tipo de Propiedad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Numero de Habitaciones");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Tamaño");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Precio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 130, -1));
        getContentPane().add(txtNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 132, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("buscar Propiedades Disponibles");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));
        getContentPane().add(txtBuscarPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 207, -1));
        getContentPane().add(txtDIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));
        getContentPane().add(txtPRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 129, -1));
        getContentPane().add(txtTAMANO, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 160, 130, -1));

        btnREGISTRAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnREGISTRAR.setText("REGISTRAR");
        getContentPane().add(btnREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, -1));

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        btnEliminarPRO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarPRO.setText("ELIMINAR");
        getContentPane().add(btnEliminarPRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, -1));

        btnCancelarPRO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelarPRO.setText("CANCELAR");
        getContentPane().add(btnCancelarPRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Estado");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        getContentPane().add(txtHABITACIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 60, -1));

        boXESTADO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boXESTADO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISPONIBLE", "NO DISPONIBLE" }));
        getContentPane().add(boXESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        boxTIPOPRO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boxTIPOPRO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "Campestre", " " }));
        getContentPane().add(boxTIPOPRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPropiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPropiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPropiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPropiedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boXESTADO;
    public javax.swing.JComboBox<String> boxTIPOPRO;
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnCancelarPRO;
    public javax.swing.JButton btnEliminarPRO;
    public javax.swing.JButton btnREGISTRAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaPropiedades;
    public javax.swing.JTextField txtBuscarPropiedad;
    public javax.swing.JTextField txtDIRECCION;
    public javax.swing.JTextField txtHABITACIONES;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtNOMBRE;
    public javax.swing.JTextField txtPRECIO;
    public javax.swing.JTextField txtTAMANO;
    // End of variables declaration//GEN-END:variables
}
