/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;


import CONTROLADOR.controladorArrendatario;
import CONTROLADOR.controladorPropiedades;
import lOGICAMODELO.logicaAlquiler;
import lOGICAMODELO.logicaArrendatario;
import lOGICAMODELO.logicaPropiedades;

import javax.swing.JFrame;

/**
 *
 * @author JHONIER ARIAS
 */
public class vistaAlquiler extends javax.swing.JFrame {


//    public static tablas tablas;

    public static vistaArrendatarios vista1arrendatarios;
    public static controladorArrendatario controladorArren;
    public static vistaAlquiler alquiler;

    public static vistaPropiedades vistaPropiedades;
    public static controladorPropiedades pro;
    public  static logicaArrendatario logicaArrendatario;
    public static logicaPropiedades  logicaPropiedades;

    /**
     * Creates new form vistaAlquiler
     */
    public vistaAlquiler() {
        initComponents();
        this.setTitle("PANEL ALQUILER");
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlquiler = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarAlquiler = new javax.swing.JButton();
        btnLlamarArrendatario = new javax.swing.JButton();
        btnLlamarPropiedades = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarAlquier = new javax.swing.JButton();
        btnActulizarAlquier = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDalquiler = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDarredatario = new javax.swing.JTextField();
        txtNombreArrendatario = new javax.swing.JTextField();
        txtxnombrePropiedad = new javax.swing.JTextField();
        boxTIPOPRO = new javax.swing.JComboBox<>();
        boXESTADO = new javax.swing.JComboBox<>();
        txtPRECIO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(1300, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaAlquiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAlquiler);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 970, 290));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel1.setText("ALQUILER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 161, 41));

        btnEliminarAlquiler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarAlquiler.setText("ELIMINAR");
        getContentPane().add(btnEliminarAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, -1));

        btnLlamarArrendatario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLlamarArrendatario.setText("ARRENDATARIOS");
        btnLlamarArrendatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlamarArrendatarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnLlamarArrendatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 240, 30));

        btnLlamarPropiedades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLlamarPropiedades.setText("PROPIEDADES");
        btnLlamarPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlamarPropiedadesActionPerformed(evt);
            }
        });
        getContentPane().add(btnLlamarPropiedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 240, -1));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 280, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("buscar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 49, 66));

        btnRegistrarAlquier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarAlquier.setText("REGISTRAR");
        getContentPane().add(btnRegistrarAlquier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btnActulizarAlquier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActulizarAlquier.setText("ACTUALIZAR ");
        getContentPane().add(btnActulizarAlquier, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("PRECIO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ESTADO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        getContentPane().add(txtIDalquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 110, 30));

        jLabel6.setText("IDENTIDICACION");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setText("NOMBRE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel8.setText("PROPIEDAD");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel9.setText("TIPO DE PROPIEDAD");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtIDarredatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDarredatarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDarredatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, -1));
        getContentPane().add(txtNombreArrendatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 150, -1));
        getContentPane().add(txtxnombrePropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 140, -1));

        boxTIPOPRO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boxTIPOPRO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "Campestre", " " }));
        getContentPane().add(boxTIPOPRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 110, -1));

        boXESTADO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boXESTADO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISPONIBLE", "NO DISPONIBLE" }));
        getContentPane().add(boXESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));
        getContentPane().add(txtPRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 129, -1));

        getAccessibleContext().setAccessibleName("ALQUILER");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLlamarArrendatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlamarArrendatarioActionPerformed
       
        
        vista1arrendatarios = new vistaArrendatarios();
                vista1arrendatarios.setVisible(true);
                vista1arrendatarios.setLocationRelativeTo(null);
                controladorArren = new controladorArrendatario(vista1arrendatarios);

                logicaArrendatario = new logicaArrendatario();
                logicaArrendatario.mostrarArrendatario(vista1arrendatarios.tablaArrendatarios);

        
        
    }//GEN-LAST:event_btnLlamarArrendatarioActionPerformed

    private void btnLlamarPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlamarPropiedadesActionPerformed

       vistaPropiedades = new vistaPropiedades();
                vistaPropiedades.setVisible(true);
                vistaPropiedades.setLocationRelativeTo(null);
                pro = new controladorPropiedades(vistaPropiedades);
                logicaPropiedades = new logicaPropiedades();
                logicaPropiedades.mostrarPropiedades(vistaPropiedades.tablaPropiedades);


    }//GEN-LAST:event_btnLlamarPropiedadesActionPerformed

    private void txtIDarredatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDarredatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDarredatarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boXESTADO;
    public javax.swing.JComboBox<String> boxTIPOPRO;
    public javax.swing.JButton btnActulizarAlquier;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEliminarAlquiler;
    public javax.swing.JButton btnLlamarArrendatario;
    public javax.swing.JButton btnLlamarPropiedades;
    public javax.swing.JButton btnRegistrarAlquier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaAlquiler;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtIDalquiler;
    public javax.swing.JTextField txtIDarredatario;
    public javax.swing.JTextField txtNombreArrendatario;
    public javax.swing.JTextField txtPRECIO;
    public javax.swing.JTextField txtxnombrePropiedad;
    // End of variables declaration//GEN-END:variables
}
