/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author JHONIER ARIAS
 */
public class vistaArrendatarios extends javax.swing.JFrame {
    
    public vistaArrendatarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArrendatarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidentificacion = new javax.swing.JTextField();
        txtNombreArrendatario = new javax.swing.JTextField();
        txtApellidoA = new javax.swing.JTextField();
        txtReferencias = new javax.swing.JTextField();
        txtContactoA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtbuscarArrendatario = new javax.swing.JTextField();
        btnRegistrarA = new javax.swing.JButton();
        btnActualizarA = new javax.swing.JButton();
        btnEliminarA = new javax.swing.JButton();
        btnCancelarA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaArrendatarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaArrendatarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 56, 564, 220));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        jLabel1.setText("ARRENDATARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 202, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Identifiacion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 94, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Contacto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 169, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Referencias");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 201, -1, -1));
        getContentPane().add(txtidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 56, 84, -1));
        getContentPane().add(txtNombreArrendatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 91, 84, -1));
        getContentPane().add(txtApellidoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 126, 84, -1));
        getContentPane().add(txtReferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 201, 84, -1));
        getContentPane().add(txtContactoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 166, 84, -1));

        jLabel7.setText("CONSULTAR");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 24, -1, -1));
        getContentPane().add(txtbuscarArrendatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 21, 182, -1));

        btnRegistrarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarA.setText("REGISTRAR");
        getContentPane().add(btnRegistrarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        btnActualizarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarA.setText("ACTUALIZAR");
        getContentPane().add(btnActualizarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        btnEliminarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarA.setText("ELIMINAR");
        getContentPane().add(btnEliminarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btnCancelarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelarA.setText("CANCELAR");
        getContentPane().add(btnCancelarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaArrendatarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaArrendatarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaArrendatarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaArrendatarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarA;
    public javax.swing.JButton btnCancelarA;
    public javax.swing.JButton btnEliminarA;
    public javax.swing.JButton btnRegistrarA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaArrendatarios;
    public javax.swing.JTextField txtApellidoA;
    public javax.swing.JTextField txtContactoA;
    public javax.swing.JTextField txtNombreArrendatario;
    public javax.swing.JTextField txtReferencias;
    public javax.swing.JTextField txtbuscarArrendatario;
    public javax.swing.JTextField txtidentificacion;
    // End of variables declaration//GEN-END:variables
}
